# Generated by Django 5.2.13 on 2026-05-03 18:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Dal',
                'verbose_name_plural': 'Dallar',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
            ],
            options={
                'verbose_name': 'Ayar',
                'verbose_name_plural': 'Ayarlar',
            },
        ),
        migrations.CreateModel(
            name='Sinif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinif', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Sınıf',
                'verbose_name_plural': 'Sınıflar',
            },
        ),
        migrations.CreateModel(
            name='SoruTuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Soru Türü',
                'verbose_name_plural': 'Soru Türleri',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('adi', models.CharField(blank=True, max_length=50, null=True)),
                ('soyadi', models.CharField(blank=True, max_length=50, null=True)),
                ('unvan', models.CharField(blank=True, max_length=50, null=True)),
                ('okul', models.CharField(blank=True, max_length=255, null=True)),
                ('calistigi_alan', models.CharField(blank=True, max_length=100, null=True)),
                ('membership_type', models.CharField(default='free', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100)),
                ('dal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dersler', to='akademi.dal')),
            ],
            options={
                'verbose_name': 'Ders',
                'verbose_name_plural': 'Dersler',
            },
        ),
        migrations.CreateModel(
            name='Modul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=200)),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moduller', to='akademi.ders')),
            ],
            options={
                'verbose_name': 'Modül',
                'verbose_name_plural': 'Modüller',
            },
        ),
        migrations.AddField(
            model_name='dal',
            name='sinif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dallar', to='akademi.sinif'),
        ),
        migrations.CreateModel(
            name='Soru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru_metni', models.TextField()),
                ('soru_resmi', models.ImageField(blank=True, null=True, upload_to='soru_resimleri/')),
                ('secenek_a', models.TextField()),
                ('secenek_b', models.TextField()),
                ('secenek_c', models.TextField()),
                ('secenek_d', models.TextField()),
                ('secenek_e', models.TextField(blank=True, null=True)),
                ('dogru_cevap', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('zorluk_seviyesi', models.CharField(choices=[('kolay', 'Kolay'), ('orta', 'Orta'), ('zor', 'Zor')], default='orta', max_length=10)),
                ('onay_durumu', models.CharField(choices=[('taslak', 'Taslak'), ('beklemede', 'Beklemede'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi')], default='onaylandi', max_length=20)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('dal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademi.dal')),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademi.ders')),
                ('modul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademi.modul')),
                ('sinif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademi.sinif')),
                ('soruyu_hazirlayan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademi.soruturu')),
            ],
            options={
                'verbose_name': 'Soru',
                'verbose_name_plural': 'Sorular',
            },
        ),
    ]
