# Generated by Django 5.2.13 on 2026-05-04 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sinif',
            options={'ordering': ['sinif'], 'verbose_name': 'Sınıf', 'verbose_name_plural': 'Sınıflar'},
        ),
        migrations.CreateModel(
            name='HataBildirimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesaj', models.TextField(verbose_name='Hata Detayı')),
                ('durum', models.CharField(choices=[('yeni', 'Yeni Bekliyor'), ('inceleniyor', 'İnceleniyor'), ('cozuldu', 'Çözüldü')], default='yeni', max_length=20)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('soru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hata_bildirimleri', to='akademi.soru')),
            ],
        ),
    ]
