# Generated by Django 5.2.13 on 2026-05-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademi', '0002_alter_sinif_options_hatabildirimi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soru',
            name='secenek_a',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soru',
            name='secenek_b',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soru',
            name='secenek_c',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soru',
            name='secenek_d',
            field=models.TextField(blank=True, null=True),
        ),
    ]
