# Generated by Django 5.2.13 on 2026-05-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademi', '0003_alter_soru_secenek_a_alter_soru_secenek_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soru',
            name='cevap_resmi',
            field=models.ImageField(blank=True, null=True, upload_to='cevap_resimleri/'),
        ),
        migrations.AddField(
            model_name='soru',
            name='klasik_cevap',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soru',
            name='dogru_cevap',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, null=True),
        ),
    ]
