# Generated by Django 5.2.13 on 2026-05-05 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademi', '0004_soru_cevap_resmi_soru_klasik_cevap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dal',
            name='sinif',
        ),
        migrations.AddField(
            model_name='ders',
            name='sinif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dersler', to='akademi.sinif'),
        ),
        migrations.AlterField(
            model_name='ders',
            name='dal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dersler', to='akademi.dal'),
        ),
        migrations.AlterField(
            model_name='soru',
            name='dal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='akademi.dal'),
        ),
    ]
