# Generated by Django 5.2.13 on 2026-05-07 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademi', '0005_remove_dal_sinif_ders_sinif_alter_ders_dal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ders',
            name='sinif',
        ),
        migrations.AddField(
            model_name='dal',
            name='sinif',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dallar', to='akademi.sinif'),
            preserve_default=False,
        ),
    ]
